# Site settings
title: "It looks hard, it’s harder than it looks!"
# email: "&#104;&#105;&#064;&#112;&#101;&#105;&#119;&#101;&#110;&#046;&#108;&#117;"
email: 				'jijin.huang2012@gmail.com'
description: 	"Jijin's front-end blog."
baseurl: 			''
url: 					'http://raomin.net'
# 文章的url链接显示
# 参数：year short_year month i_month day i_day title categories
# pretty􏳈: /:categories/:year/:month/:day/:title/
# none􏳈: /:categories/:title.html
permalink: /:year/:title

# Social account
twitter:  		'jijin_huang'
weibo:    		'2181906002'
github:   		'tclz'
# facebook: jijin.huang.35
# codepen:  username
# dribbble: username

# Comment
disqus_shortname: 'jijinblog'

# Google Analytics
# google_analytics: userinfo


# Build settings
markdown: kramdown
  # input: GFM
  # syntax_highlighter: 'rouge'

sass:
  style: compressed

gems:
  - jekyll-sitemap
